/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.nio.file.Paths;
import java.util.NoSuchElementException;
import java.util.Scanner;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import static java.util.regex.Pattern.compile;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author User
 */
public class BuscaClientePedido extends javax.swing.JFrame {

    /**
     * Creates new form BuscaClientePedido
     */
    
    String nomeCliente;
    
    private static Scanner input;
    public BuscaClientePedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nomeClienteBuscaPedido = new javax.swing.JTextField();
        buscarClientePedidopq = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        movelBusca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        buscaPedido = new javax.swing.JTextField();

        jLabel1.setText("Cliente :");

        buscarClientePedidopq.setText("Buscar");
        buscarClientePedidopq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarClientePedidopqActionPerformed(evt);
            }
        });

        jLabel2.setText("Movel:");

        jLabel3.setText("Pedido:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeClienteBuscaPedido, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(buscarClientePedidopq, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(movelBusca)
                    .addComponent(buscaPedido))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeClienteBuscaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(movelBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buscaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(buscarClientePedidopq)
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
  
    private void buscarClientePedidopqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarClientePedidopqActionPerformed
        // TODO add your handling code here:
        // Recebe o texto no campo de busca do 
        String nome= nomeClienteBuscaPedido.getText();
        String movel= movelBusca.getText();
        String pedido= buscaPedido.getText();
        String caminho;
        int sw;
        if(movel != null){
            caminho= ("C:/sabineM/arq_01.txt");
            sw=1;
        }else if(nome != null){
            caminho= ("C:/sabineM/arq_02.txt");
            sw=2;
        }else if(pedido!= null){
            caminho= ("C:/sabineM/arq_03.txt");
            sw=3;
        }else{
            caminho =null;
            sw=0;
        }
        switch(sw){
            case 1:
    
  try{
        input = new Scanner(Paths.get(caminho));
    }catch (IOException ioException){
        System.err.println("Error opening file. Terminating.");
        System.exit(1);
    }
    //Pattern busca o termo recebido na váriavel nome
    Pattern termo= compile(nome) ;
    JOptionPane.showMessageDialog(null, termo);
try{
    
    while (input.hasNext()) // enquanto houver mais para ler
    {
        String l= input.next();//A variável l recebe o próximo termo
        
        if(l.equals(nome)){ //se l for igual ao nome  
        
        
        //TODO 
        
        
        nomeCliente= l;
        JOptionPane.showMessageDialog(null, l);
       
        
        break;
        }else{
            
            
        }
        
        
    }// fecha while
    
    
}catch (NoSuchElementException elementException){
    System.err.println("File improperly formed. Terminating.");
}
   if (input != null){
        input.close();
    }
   
   
    }//GEN-LAST:event_buscarClientePedidopqActionPerformed
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscaClientePedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscaClientePedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscaClientePedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscaClientePedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscaClientePedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buscaPedido;
    private javax.swing.JButton buscarClientePedidopq;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField movelBusca;
    private javax.swing.JTextField nomeClienteBuscaPedido;
    // End of variables declaration//GEN-END:variables

   
}
