/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTextField;
import java.io.BufferedWriter;
import java.io.*;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author PC
 */


public class TelaCadastroMoveis extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCadastroMoveis
     */
    
     
    public TelaCadastroMoveis() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jPanelCadastroMoveis1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NomeMovelCadastro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campoPrecoCadastro = new javax.swing.JTextField();
        campoPesoCadastro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tamanhoEnvioCadastro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        qtdCad1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        materialCad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        plataformaCad1 = new javax.swing.JTextField();
        salvarcadMov = new javax.swing.JButton();
        precoCad2 = new javax.swing.JTextField();
        plataformaCad2 = new javax.swing.JTextField();
        precoCad3 = new javax.swing.JTextField();
        plataformaCad3 = new javax.swing.JTextField();
        qtdCad2 = new javax.swing.JTextField();
        materialCad2 = new javax.swing.JTextField();
        qtdCad3 = new javax.swing.JTextField();
        materialCad3 = new javax.swing.JTextField();
        qtdCad4 = new javax.swing.JTextField();
        materialCad4 = new javax.swing.JTextField();
        qtdCad5 = new javax.swing.JTextField();
        materialCad5 = new javax.swing.JTextField();

        jTextField3.setText("jTextField3");

        jLabel1.setText("Móvel");

        jLabel2.setText("Preço");

        jLabel3.setText("Tamanho Para Envio");

        tamanhoEnvioCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tamanhoEnvioCadastroActionPerformed(evt);
            }
        });

        jLabel4.setText("Peso");

        jLabel5.setText("Material");

        qtdCad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtdCad1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Qtd");

        jLabel7.setText("Plataforma");

        salvarcadMov.setText("Salvar");
        salvarcadMov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarcadMovActionPerformed(evt);
            }
        });

        precoCad3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precoCad3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCadastroMoveis1Layout = new javax.swing.GroupLayout(jPanelCadastroMoveis1);
        jPanelCadastroMoveis1.setLayout(jPanelCadastroMoveis1Layout);
        jPanelCadastroMoveis1Layout.setHorizontalGroup(
            jPanelCadastroMoveis1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroMoveis1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastroMoveis1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroMoveis1Layout.createSequentialGroup()
                        .addGroup(jPanelCadastroMoveis1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(qtdCad1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(qtdCad5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelCadastroMoveis1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadastroMoveis1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanelCadastroMoveis1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(materialCad5, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                    .addComponent(materialCad, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(materialCad2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(materialCad3)
                                    .addComponent(materialCad4))
                                .addGap(0, 220, Short.MAX_VALUE))
                            .addGroup(jPanelCadastroMoveis1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(salvarcadMov)
                                .addGap(142, 142, 142))))
                    .addGroup(jPanelCadastroMoveis1Layout.createSequentialGroup()
                        .addGroup(jPanelCadastroMoveis1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadastroMoveis1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(qtdCad2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                .addComponent(qtdCad3))
                            .addComponent(jLabel1)
                            .addComponent(NomeMovelCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelCadastroMoveis1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(65, 65, 65)
                                .addComponent(jLabel7))
                            .addGroup(jPanelCadastroMoveis1Layout.createSequentialGroup()
                                .addGroup(jPanelCadastroMoveis1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(precoCad3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(precoCad2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoPrecoCadastro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelCadastroMoveis1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(plataformaCad1, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                    .addComponent(plataformaCad2)
                                    .addComponent(plataformaCad3)))
                            .addComponent(qtdCad4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelCadastroMoveis1Layout.createSequentialGroup()
                                .addGroup(jPanelCadastroMoveis1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tamanhoEnvioCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(jPanelCadastroMoveis1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoPesoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 208, Short.MAX_VALUE))))
        );
        jPanelCadastroMoveis1Layout.setVerticalGroup(
            jPanelCadastroMoveis1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroMoveis1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NomeMovelCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroMoveis1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addGap(12, 12, 12)
                .addGroup(jPanelCadastroMoveis1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoPrecoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plataformaCad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastroMoveis1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precoCad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plataformaCad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastroMoveis1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precoCad3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plataformaCad3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanelCadastroMoveis1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastroMoveis1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tamanhoEnvioCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoPesoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroMoveis1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(salvarcadMov))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroMoveis1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(materialCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qtdCad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastroMoveis1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtdCad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(materialCad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastroMoveis1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtdCad3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(materialCad3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroMoveis1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtdCad4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(materialCad4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastroMoveis1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(materialCad5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qtdCad5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCadastroMoveis1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCadastroMoveis1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void precoCad3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precoCad3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precoCad3ActionPerformed

    private void salvarcadMovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarcadMovActionPerformed
        // TODO add your handling code here:
        // As variáveis recebem o texto dos campos
       TelaCadastroMoveis lista= new TelaCadastroMoveis();
       String nomeMovel = lista.getNomeMovelCadastro().getText();
       String pesoCadMovel= lista.getCampoPesoCadastro().getText();
       String precoCadMovel1= lista.getCampoPrecoCadastro().getText();
       String precoCadMovel2= lista.getCampoPrecoCadastro().getText();
       String precoCadMovel3= lista.getCampoPrecoCadastro().getText();
       String plataformaCad1= lista.getPlataformaCad1().getText();
       String plataformaCad2= lista.getPlataformaCad2().getText();
       String plataformaCad3= lista.getPlataformaCad3().getText();
       String tamanhoCad= lista.getTamanhoEnvioCadastro().getText();
       String qtdCad1= lista.getQtdCad1().getText();
       String qtdCad2= lista.getQtdCad2().getText();
       String qtdCad3= lista.getQtdCad3().getText();
       String qtdCad4= lista.getQtdCad4().getText();
       String qtdCad5= lista.getQtdCad5().getText();
       String materialCad1= lista.getMaterialCad().getText();
       String materialCad2= lista.getMaterialCad2().getText();
       String materialCad3= lista.getMaterialCad3().getText();
       String materialCad4= lista.getMaterialCad4().getText();
       String materialCad5= lista.getMaterialCad5().getText();
       
        
        try {
            
          //Escritor instanciado abre o arquivo txt  
          FileWriter  fw = new FileWriter ("C:/sabineM/arq_01.txt", true);
          BufferedWriter bw = new BufferedWriter( fw );
          
          bw.write("Móvel: " + NomeMovelCadastro.getText()+";");
          
          bw.write("Plataforma: " + this.plataformaCad1.getText()+";");
          
          bw.write("Preço: " + campoPrecoCadastro.getText()+";");
        
          bw.write("Plataforma: " + this.plataformaCad2.getText()+";");
          
          bw.write("Preço: " + this.precoCad2.getText()+";");
          
          bw.write("Plataforma: " + this.plataformaCad3.getText()+";");
          bw.write("Preço: " + this.precoCad3.getText()+";");
          
          bw.write("Material" +";");
          
          bw.write(this.qtdCad1.getText()+ " " + this.materialCad.getText()+";" );
          
          bw.write(this.qtdCad2.getText()+ " " + this.materialCad2.getText()+";" );
          
          bw.write(this.qtdCad3.getText()+ " " + this.materialCad3.getText() +";");
          
          bw.write(this.qtdCad4.getText()+ " " + this.materialCad4.getText() +";");
          
          bw.write(this.qtdCad5.getText()+ " " + this.materialCad5.getText()+";" );
        
          
          JOptionPane.showMessageDialog(null, "Tá salvo ");
          
          bw.close( );
          fw.close( );
        } catch (IOException ex) {
            Logger.getLogger(TelaCadastroMoveis.class.getName()).log(Level.SEVERE, null, ex);
        }

        
        
    }//GEN-LAST:event_salvarcadMovActionPerformed

    private void qtdCad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtdCad1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtdCad1ActionPerformed

    private void tamanhoEnvioCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tamanhoEnvioCadastroActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_tamanhoEnvioCadastroActionPerformed

    
    
    
    
     
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NomeMovelCadastro;
    private javax.swing.JTextField campoPesoCadastro;
    private javax.swing.JTextField campoPrecoCadastro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    javax.swing.JPanel jPanelCadastroMoveis1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField materialCad;
    private javax.swing.JTextField materialCad2;
    private javax.swing.JTextField materialCad3;
    private javax.swing.JTextField materialCad4;
    private javax.swing.JTextField materialCad5;
    private javax.swing.JTextField plataformaCad1;
    private javax.swing.JTextField plataformaCad2;
    private javax.swing.JTextField plataformaCad3;
    private javax.swing.JTextField precoCad2;
    private javax.swing.JTextField precoCad3;
    private javax.swing.JTextField qtdCad1;
    private javax.swing.JTextField qtdCad2;
    private javax.swing.JTextField qtdCad3;
    private javax.swing.JTextField qtdCad4;
    private javax.swing.JTextField qtdCad5;
    private javax.swing.JButton salvarcadMov;
    private javax.swing.JTextField tamanhoEnvioCadastro;
    // End of variables declaration//GEN-END:variables

    public JTextField getNomeMovelCadastro() {
        return NomeMovelCadastro;
    }

    public void setNomeMovelCadastro(JTextField NomeMovelCadastro) {
        this.NomeMovelCadastro = NomeMovelCadastro;
    }

    public JTextField getCampoPesoCadastro() {
        return campoPesoCadastro;
    }

    public void setCampoPesoCadastro(JTextField campoPesoCadastro) {
        this.campoPesoCadastro = campoPesoCadastro;
    }

    public JTextField getCampoPrecoCadastro() {
        return campoPrecoCadastro;
    }

    public void setCampoPrecoCadastro(JTextField campoPrecoCadastro) {
        this.campoPrecoCadastro = campoPrecoCadastro;
    }

    public JPanel getjPanelCadastroMoveis1() {
        return jPanelCadastroMoveis1;
    }

    public void setjPanelCadastroMoveis1(JPanel jPanelCadastroMoveis1) {
        this.jPanelCadastroMoveis1 = jPanelCadastroMoveis1;
    }

    public JTextField getjTextField3() {
        return jTextField3;
    }

    public void setjTextField3(JTextField jTextField3) {
        this.jTextField3 = jTextField3;
    }

    public JTextField getMaterialCad() {
        return materialCad;
    }

    public void setMaterialCad(JTextField materialCad) {
        this.materialCad = materialCad;
    }

    public JTextField getMaterialCad2() {
        return materialCad2;
    }

    public void setMaterialCad2(JTextField materialCad2) {
        this.materialCad2 = materialCad2;
    }

    public JTextField getMaterialCad3() {
        return materialCad3;
    }

    public void setMaterialCad3(JTextField materialCad3) {
        this.materialCad3 = materialCad3;
    }

    public JTextField getMaterialCad4() {
        return materialCad4;
    }

    public void setMaterialCad4(JTextField materialCad4) {
        this.materialCad4 = materialCad4;
    }

    public JTextField getMaterialCad5() {
        return materialCad5;
    }

    public void setMaterialCad5(JTextField materialCad5) {
        this.materialCad5 = materialCad5;
    }

    public JTextField getPlataformaCad1() {
        return plataformaCad1;
    }

    public void setPlataformaCad1(JTextField plataformaCad1) {
        this.plataformaCad1 = plataformaCad1;
    }

    public JTextField getPlataformaCad2() {
        return plataformaCad2;
    }

    public void setPlataformaCad2(JTextField plataformaCad2) {
        this.plataformaCad2 = plataformaCad2;
    }

    public JTextField getPlataformaCad3() {
        return plataformaCad3;
    }

    public void setPlataformaCad3(JTextField plataformaCad3) {
        this.plataformaCad3 = plataformaCad3;
    }

    public JTextField getPrecoCad2() {
        return precoCad2;
    }

    public void setPrecoCad2(JTextField precoCad2) {
        this.precoCad2 = precoCad2;
    }

    public JTextField getPrecoCad3() {
        return precoCad3;
    }

    public void setPrecoCad3(JTextField precoCad3) {
        this.precoCad3 = precoCad3;
    }

    public JTextField getQtdCad1() {
        return qtdCad1;
    }

    public void setQtdCad1(JTextField qtdCad1) {
        this.qtdCad1 = qtdCad1;
    }

    public JTextField getQtdCad2() {
        return qtdCad2;
    }

    public void setQtdCad2(JTextField qtdCad2) {
        this.qtdCad2 = qtdCad2;
    }

    public JTextField getQtdCad3() {
        return qtdCad3;
    }

    public void setQtdCad3(JTextField qtdCad3) {
        this.qtdCad3 = qtdCad3;
    }

    public JTextField getQtdCad4() {
        return qtdCad4;
    }

    public void setQtdCad4(JTextField qtdCad4) {
        this.qtdCad4 = qtdCad4;
    }

    public JTextField getQtdCad5() {
        return qtdCad5;
    }

    public void setQtdCad5(JTextField qtdCad5) {
        this.qtdCad5 = qtdCad5;
    }

    public JButton getSalvarcadMov() {
        return salvarcadMov;
    }

    public void setSalvarcadMov(JButton salvarcadMov) {
        this.salvarcadMov = salvarcadMov;
    }

    public JTextField getTamanhoEnvioCadastro() {
        return tamanhoEnvioCadastro;
    }

    public void setTamanhoEnvioCadastro(JTextField tamanhoEnvioCadastro) {
        this.tamanhoEnvioCadastro = tamanhoEnvioCadastro;
    }

    private void close() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    
}
